// frontend/src/lib/Layout.svelte
<script lang="ts">
    export let currentPath: string;
    export let navigate: (path: string) => void;
    export let links: Array<{ path: string; label: string }> = [];
</script>

<div class="app-layout">
    <header class="top-nav">
        <nav aria-label="Primary navigation">
            {#each links as link}
                <a
                    href={link.path}
                    class:active={currentPath === link.path}
                    on:click|preventDefault={() => navigate(link.path)}
                >
                    {link.label}
                </a>
            {/each}
        </nav>
    </header>

    <main class="page-content">
        <slot />
    </main>
</div>

<style>
    .app-layout {
        min-height: 100vh;
    }

    .top-nav {
        position: sticky;
        top: 0;
        z-index: 10;
        border-bottom: 1px solid #d0d7de;
        background: #ffffff;
        padding: 0.75rem 1rem;
    }

    nav a {
        color: #4d4f53;
        font-weight: 500;
        margin-right: 1rem;
        text-decoration: none;
    }

    nav a.active {
        color: #0f3f88;
    }

    .page-content {
        padding: 1rem;
    }
</style>

// react-frontend/src/components/layout.tsx
import { Link, useRouterState } from '@tanstack/react-router'
import type { ReactNode } from 'react'

import { cn } from '#/lib/utils'

const navLinks = [{ path: '/', label: 'Home' }] as const

const normalizePath = (path: string) =>
  path === '/' ? '/' : path.replace(/\/+$/, '') || '/'

export function AppLayout({ children }: { children: ReactNode }) {
  const currentPath = useRouterState({
    select: (state) => normalizePath(state.location.pathname),
  })

  return (
    <div className="min-h-screen">
      <header className="sticky top-0 z-10 border-b border-[#d0d7de] bg-white px-4 py-3">
        <nav aria-label="Primary navigation">
          {navLinks.map((link) => (
            <Link
              key={link.path}
              to={link.path}
              className={cn(
                'mr-4 font-medium no-underline',
                currentPath === link.path ? 'text-[#0f3f88]' : 'text-[#4d4f53]',
              )}
            >
              {link.label}
            </Link>
          ))}
        </nav>
      </header>
      <main className="p-4">{children}</main>
    </div>
  )
}
